# Generated by Django 3.1.7 on 2023-03-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_number', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('car_brand', models.CharField(max_length=50)),
                ('car_color', models.CharField(max_length=20)),
                ('car_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('ifcar', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('enter_time', models.DateField(auto_now_add=True)),
                ('out_time', models.DateField()),
                ('car_number', models.CharField(max_length=20)),
                ('stay_time', models.TimeField()),
            ],
        ),
    ]
