# Generated by Django 3.1.7 on 2023-03-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='ifcar',
        ),
    ]
