# Generated by Django 3.1.7 on 2023-03-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecar', '0002_remove_employee_ifcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='stay_time',
        ),
        migrations.AlterField(
            model_name='records',
            name='enter_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='out_time',
            field=models.DateTimeField(),
        ),
    ]
