# Generated by Django 3.1.7 on 2023-03-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecar', '0004_auto_20230308_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='out_time',
            field=models.DateTimeField(default=None),
        ),
    ]
