# Generated by Django 3.1.7 on 2023-03-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecar', '0006_auto_20230308_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='out_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
